import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import ToastContainer from '@/components/ToastContainer';
import { cookies } from 'next/headers';
import { AUTH_TOKEN } from '@/constants';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const cookie = await cookies();
  const token = cookie.get(AUTH_TOKEN)?.value
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
      >
        <Navbar token={token}/>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
